version: "3.9"

services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    expose:
      - "3000"
    depends_on:
      - "db"

  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "robot-world"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "robot-world"
    expose:
      - "3306"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
