#Car Models
Model.create(name:"Peugeot")
Model.create(name:"Renault")
Model.create(name:"Fiat")
Model.create(name:"Hyundai")
Model.create(name:"Ferrari")
Model.create(name:"Mustang")
Model.create(name:"Honda")
Model.create(name:"Porsche")
Model.create(name:"Kia")
Model.create(name:"Ford")

#Part Types - Wheels, Chasis, Engine, etc
PartType.create(name:"Chasis", assembly_line: "Basic_Structure")
PartType.create(name:"W1", assembly_line: "Basic_Structure")
PartType.create(name:"W2", assembly_line: "Basic_Structure")
PartType.create(name:"W3", assembly_line: "Basic_Structure")
PartType.create(name:"W4", assembly_line: "Basic_Structure")
PartType.create(name:"Engine", assembly_line: "Basic_Structure")
PartType.create(name:"Seat1", assembly_line: "Basic_Structure")
PartType.create(name:"Seat2", assembly_line: "Basic_Structure")
PartType.create(name:"Laser", assembly_line: "Electronic_Devices")